disabled_rules: # rule identifiers to exclude from running
  - trailing_whitespace
included: 
  - Application
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Build
  